-- ============================================================
-- ART MEMORY 2.0 — COMPLETE SUPABASE SETUP
-- Jalankan SELURUH file ini di Supabase SQL Editor.
--
-- Yang disiapkan:
-- 1) Profile + theme studio
-- 2) Gallery: Image Roblox / Art Roblox / SS Roblox
-- 3) Like unik per visitor
-- 4) View unik per visitor per hari
-- 5) Download counter
-- 6) Request HD/Edit
-- 7) Admin access berbasis Supabase Auth
-- 8) RLS aman untuk admin vs pengunjung
-- 9) Storage buckets + policies
-- 10) Realtime untuk statistik/gallery/request
-- ============================================================

create extension if not exists pgcrypto;

-- ---------- ADMIN ----------
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users a
    where a.user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

drop policy if exists "admin users read own" on public.admin_users;
create policy "admin users read own" on public.admin_users
for select to authenticated
using (user_id = auth.uid());

drop policy if exists "admin users manage" on public.admin_users;
create policy "admin users manage" on public.admin_users
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- ---------- PROFILE / THEME ----------
create table if not exists public.profile (
  id bigint primary key,
  name text not null default 'Art Memory',
  bio text not null default 'Welcome to the gallery of memories.',
  avatar_url text,
  avatar_path text,
  avatar_position text not null default '50% 50%',
  avatar_zoom numeric(4,2) not null default 1.00,
  username text not null default '@KanjengCicak',
  user_id text not null default '',
  favorite_game text not null default '',
  roblox_url text not null default '',
  about text not null default '',
  tiktok_url text not null default '',
  theme_color text not null default '#5b8cff',
  theme_preset text not null default 'aurora',
  theme_radius integer not null default 24,
  image_contact text not null default 'Kirim request lewat formulir di bawah.',
  updated_at timestamptz not null default now()
);

alter table public.profile add column if not exists avatar_path text;
alter table public.profile add column if not exists avatar_zoom numeric(4,2) not null default 1.00;
alter table public.profile add column if not exists theme_preset text not null default 'aurora';
alter table public.profile add column if not exists theme_radius integer not null default 24;
alter table public.profile add column if not exists theme_color text not null default '#5b8cff';
alter table public.profile add column if not exists image_contact text not null default 'Kirim request lewat formulir di bawah.';

insert into public.profile (id,name,bio)
values (1,'Art Memory','Welcome to the gallery of memories.')
on conflict (id) do nothing;

alter table public.profile enable row level security;
drop policy if exists "public read profile" on public.profile;
create policy "public read profile" on public.profile
for select to anon, authenticated using (true);

drop policy if exists "admin update profile" on public.profile;
create policy "admin update profile" on public.profile
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin insert profile" on public.profile;
create policy "admin insert profile" on public.profile
for insert to authenticated with check (public.is_admin());

-- ---------- AUTO TIMESTAMPS ----------
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profile_touch_updated_at on public.profile;
create trigger profile_touch_updated_at before update on public.profile
for each row execute function public.touch_updated_at();

-- ---------- PHOTOS ----------
create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  description text not null default '',
  image_url text not null,
  image_path text,
  likes bigint not null default 0,
  views bigint not null default 0,
  downloads bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint photos_category_check check (category in ('art','screenshots','edits','fav_friend'))
);

alter table public.photos add column if not exists image_path text;
drop trigger if exists photos_touch_updated_at on public.photos;
create trigger photos_touch_updated_at before update on public.photos
for each row execute function public.touch_updated_at();
alter table public.photos add column if not exists updated_at timestamptz not null default now();

alter table public.photos drop constraint if exists photos_category_check;
alter table public.photos add constraint photos_category_check check (category in ('art','screenshots','edits','fav_friend'));

alter table public.photos enable row level security;
drop policy if exists "public read photos" on public.photos;
create policy "public read photos" on public.photos
for select to anon, authenticated using (true);

drop policy if exists "admin insert photos" on public.photos;
create policy "admin insert photos" on public.photos
for insert to authenticated with check (public.is_admin());

drop policy if exists "admin update photos" on public.photos;
create policy "admin update photos" on public.photos
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin delete photos" on public.photos;
create policy "admin delete photos" on public.photos
for delete to authenticated using (public.is_admin());

-- ---------- LIKES ----------
create table if not exists public.photo_likes (
  photo_id bigint not null references public.photos(id) on delete cascade,
  visitor_id uuid not null,
  created_at timestamptz not null default now(),
  primary key (photo_id, visitor_id)
);

alter table public.photo_likes enable row level security;
drop policy if exists "no public direct like writes" on public.photo_likes;
-- Like insert dilakukan melalui RPC security-definer, bukan direct insert dari browser.

-- ---------- VIEWS ----------
create table if not exists public.photo_views (
  photo_id bigint not null references public.photos(id) on delete cascade,
  visitor_id uuid not null,
  viewed_on date not null default current_date,
  created_at timestamptz not null default now(),
  primary key (photo_id, visitor_id, viewed_on)
);

alter table public.photo_views enable row level security;
-- View insert dilakukan melalui RPC security-definer.

-- ---------- DOWNLOADS ----------
create table if not exists public.photo_downloads (
  photo_id bigint not null references public.photos(id) on delete cascade,
  visitor_id uuid not null,
  downloaded_on date not null default current_date,
  created_at timestamptz not null default now(),
  primary key (photo_id, visitor_id, downloaded_on)
);

alter table public.photo_downloads enable row level security;

-- ---------- REQUEST HD / EDIT ----------
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null default 'Pengunjung',
  contact text not null default '',
  message text not null,
  status text not null default 'new' check (status in ('new','read')),
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;
drop policy if exists "public insert contact messages" on public.contact_messages;
create policy "public insert contact messages" on public.contact_messages
for insert to anon, authenticated
with check (length(trim(message)) between 2 and 800);

drop policy if exists "admin read contact messages" on public.contact_messages;
create policy "admin read contact messages" on public.contact_messages
for select to authenticated using (public.is_admin());

drop policy if exists "admin update contact messages" on public.contact_messages;
create policy "admin update contact messages" on public.contact_messages
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin delete contact messages" on public.contact_messages;
create policy "admin delete contact messages" on public.contact_messages
for delete to authenticated using (public.is_admin());

-- ---------- COUNTER FUNCTIONS ----------
create or replace function public.add_like(p_photo_id bigint, p_visitor_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted boolean := false;
  new_count bigint := 0;
begin
  if p_photo_id is null or p_visitor_id is null then
    raise exception 'photo_id and visitor_id are required';
  end if;

  insert into public.photo_likes(photo_id, visitor_id)
  values (p_photo_id, p_visitor_id)
  on conflict (photo_id, visitor_id) do nothing;
  inserted := found;

  update public.photos p
  set likes = (select count(*) from public.photo_likes l where l.photo_id = p_photo_id),
      updated_at = now()
  where p.id = p_photo_id
  returning likes into new_count;

  return jsonb_build_object('liked', inserted, 'likes', coalesce(new_count,0));
end;
$$;

create or replace function public.add_view(p_photo_id bigint, p_visitor_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted boolean := false;
  new_count bigint := 0;
begin
  if p_photo_id is null or p_visitor_id is null then
    raise exception 'photo_id and visitor_id are required';
  end if;

  insert into public.photo_views(photo_id, visitor_id, viewed_on)
  values (p_photo_id, p_visitor_id, current_date)
  on conflict (photo_id, visitor_id, viewed_on) do nothing;
  inserted := found;

  update public.photos p
  set views = (select count(*) from public.photo_views v where v.photo_id = p_photo_id),
      updated_at = now()
  where p.id = p_photo_id
  returning views into new_count;

  return jsonb_build_object('counted', inserted, 'views', coalesce(new_count,0));
end;
$$;

create or replace function public.add_download(p_photo_id bigint, p_visitor_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted boolean := false;
  new_count bigint := 0;
begin
  if p_photo_id is null or p_visitor_id is null then
    raise exception 'photo_id and visitor_id are required';
  end if;

  insert into public.photo_downloads(photo_id, visitor_id, downloaded_on)
  values (p_photo_id, p_visitor_id, current_date)
  on conflict (photo_id, visitor_id, downloaded_on) do nothing;
  inserted := found;

  update public.photos p
  set downloads = (select count(*) from public.photo_downloads d where d.photo_id = p_photo_id),
      updated_at = now()
  where p.id = p_photo_id
  returning downloads into new_count;

  return jsonb_build_object('counted', inserted, 'downloads', coalesce(new_count,0));
end;
$$;

revoke all on function public.add_like(bigint,uuid) from public;
revoke all on function public.add_view(bigint,uuid) from public;
revoke all on function public.add_download(bigint,uuid) from public;
grant execute on function public.add_like(bigint,uuid) to anon, authenticated;
grant execute on function public.add_view(bigint,uuid) to anon, authenticated;
grant execute on function public.add_download(bigint,uuid) to anon, authenticated;

-- ---------- CLEAN OLD COUNTERS / CONSISTENCY ----------
update public.photos p set likes=(select count(*) from public.photo_likes l where l.photo_id=p.id);
update public.photos p set views=(select count(*) from public.photo_views v where v.photo_id=p.id);
update public.photos p set downloads=(select count(*) from public.photo_downloads d where d.photo_id=p.id);

-- ---------- STORAGE ----------
insert into storage.buckets (id,name,public)
values ('gallery','gallery',true)
on conflict (id) do update set public=true;

insert into storage.buckets (id,name,public)
values ('avatars','avatars',true)
on conflict (id) do update set public=true;

drop policy if exists "public read gallery objects" on storage.objects;
create policy "public read gallery objects" on storage.objects
for select to anon, authenticated
using (bucket_id in ('gallery','avatars'));

drop policy if exists "admin upload gallery objects" on storage.objects;
create policy "admin upload gallery objects" on storage.objects
for insert to authenticated
with check (bucket_id in ('gallery','avatars') and public.is_admin());

drop policy if exists "admin update gallery objects" on storage.objects;
create policy "admin update gallery objects" on storage.objects
for update to authenticated
using (bucket_id in ('gallery','avatars') and public.is_admin())
with check (bucket_id in ('gallery','avatars') and public.is_admin());

drop policy if exists "admin delete gallery objects" on storage.objects;
create policy "admin delete gallery objects" on storage.objects
for delete to authenticated
using (bucket_id in ('gallery','avatars') and public.is_admin());

-- ---------- REALTIME ----------
-- Realtime diperlukan supaya Like/View/galeri/request bisa ikut berubah tanpa refresh.
do $$
begin
  if exists (select 1 from pg_publication where pubname='supabase_realtime') then
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='photos') then
      alter publication supabase_realtime add table public.photos;
    end if;
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='contact_messages') then
      alter publication supabase_realtime add table public.contact_messages;
    end if;
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='profile') then
      alter publication supabase_realtime add table public.profile;
    end if;
  end if;
end $$;

-- ---------- INDEXES ----------
create index if not exists photos_category_created_idx on public.photos(category, created_at desc);
create index if not exists photo_likes_photo_idx on public.photo_likes(photo_id);
create index if not exists photo_views_photo_idx on public.photo_views(photo_id);
create index if not exists photo_downloads_photo_idx on public.photo_downloads(photo_id);
create index if not exists contact_messages_created_idx on public.contact_messages(created_at desc);

-- ============================================================
-- SETUP ADMIN (WAJIB SEKALI)
-- ============================================================
-- Password TIDAK disimpan di tabel aplikasi.
-- Buat akun admin di Supabase Dashboard:
-- Authentication → Users → Add user → isi email + password.
-- Setelah user dibuat, copy UUID user tersebut dan jalankan:
--
-- insert into public.admin_users(user_id, username)
-- values ('UUID_DARI_AUTH_USERS', 'KanjengCicak')
-- on conflict (user_id) do update set username=excluded.username;
--
-- Setelah itu login lewat login.html menggunakan EMAIL + PASSWORD
-- yang tersimpan/ditangani Supabase Auth.
-- Jangan pernah menaruh service_role key di frontend.
-- ============================================================
